- hosts: webservers
  become: yes
  tasks:
    - name: Install datadog agent
      import_role:
        name: datadog.dd.agent
      vars:
        datadog_api_key: '{{ DD_API_KEY }}'
        datadog_site: '{{ dd_site }}'
        datadog_checks:
          http_check:
            instances:
              - name: app
                url: '{{ app_localhost }}'
