$ANSIBLE_VAULT;1.1;AES256
30383833363861316461623036363930363038376432343736623332623439386262633137333061
6434343361336535363961353035633866373264353039640a636530383961356438343635653065
64633562366435613932373362613831303139623662616439333462653139633432303830636339
3430636165633765390a636130646265323662303061383831313133646536383361383261323161
33633535323232303763663832613466343864333634623536633034313633333536373334633830
63616333663666653433346230333564663039393066343238366266396136393731333036343036
37633137646539626663373863323336323832376132393066393236373937316433396138653064
39646338666431643765336365663331396239363765663963666239373732633630333839353237
39356463636336353837366264373137663035353339343835326234623062376230
