$ANSIBLE_VAULT;1.1;AES256
36383366643365613462353464653434613236653966353034383438613933373437396464336333
6165623536636539626637643365663739366161313064640a373361646664323562393030343938
61316135326235396431626161616535666538383263653438313963333763346465356564323235
6631373133363666320a653965656333666436623234323463663637313239306432393461356135
32353963643763386130353964303637633135336661356335643733653264353161393865353866
65306638633666316436363862623530376263636165623661626239326636343366363534653564
37386438646562306164343062306430623435363938386234323665373662333331393137396363
64316334383165396436666665323737656461373730346664376333613735313565653530326132
30303761653231366236613736666262306532656536633862646666326537333537303865666465
62366132383563316535306630353233323630613536656538343334316364323337313165323263
38633662333532336533383966613135353739363362616464363739393538363761303965343832
36356435396166343463323335616361303537303639303262646439383565653330393936646663
62616664396636643234313734323661383435666166636132393763336433643036303863626461
37656635303962333865306636633530333535303266316639393837346239306539343836623565
31656261393230656332393434306163313634313232306631346363376364373531616265326533
63613831656130663032633565666135396437643331383635346536666338623739326565663465
3866
