$ANSIBLE_VAULT;1.1;AES256
65376465643666646364386334383961633361363930666563363238346364646566326539303764
3432333933373332346631653762373834616136346164310a306135653938346533303132666431
39343133393631353635333064333531623165623537613066383937613466626261663437373439
3632376635626633320a643062373536396562333836323639363161313366626462613763316165
33323565363664666464663239616262323262623862383637643038326166656534383038393934
32333733636232363062663235613862386366613735343534366462363836333631333536623330
37373432343735353735353161393063323830383862306330623730653730306164663934613963
38643431633661663337326165373335613263373666316533353637336538343232393834366331
36653561636661383166336133663037393635326339333365613135643062386631316534366365
65656637663530356662313363653462353238633364333166383330323438643437383633616437
63326136656162633430393538316233366235376263613032366231633632366330623162303763
35303739666130343963653031326566613438323362656638326530623162393138366163356264
38336339656530613363346334346638396330653463353032633236623639373662643439643437
61653838613266626639316634326337346138626562393966626566376535616665633138623338
62366266616236366332386435393664373533366435393561643837616165323139306436623033
39363663663364376431663362303339663934636334306433333538376366393732363238376163
31363562643966346363353939333237353139316433353464323833363835626266653963663539
36323439383231306135323366313264623763343237326466373461323131336437373537656131
653638663133306635633535373338303335
